/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-29-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class cls_cmx_newclass {
    public cls_cmx_newclass() {
        system.debug('Inside constructor');
    }
    public string returnText(string parameter){
        return parameter;
    }
}